### ISSUE TITLE
GLIBC_2.29 required

### ISSUE THREAD

**Issue by dhruvAG4291** [vinecopulib/pyvinecopulib#101]
While import this library, I am getting the following error:
`
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found`

```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
```

**Comment by tnagler** [comment]
We've seen something like that earlier in #92. We do not require a GLIBC version anywhere, this is an issue of your compiler setup. Probably python/cpython was compiled using a different toolchain than the one you're using to compile pyvinecopulib.
