### ISSUE TITLE
API for inference

### ISSUE THREAD

**Issue by kkarrancsu** [vinecopulib/pyvinecopulib#104]
Is there a way to perform inference on the Vinecop objects?

**Comment by tnagler** [comment]
Can you be a bit more specific?

**Comment by kkarrancsu** [comment]
Yep - suppose I have a vine copula object of 3 variables, u1, u2, and u3. Given a value of u1 and u2, I want to get the distribution of u3?

**Comment by tnagler** [comment]
This can be done with the [rosenblatt transform](https://vinecopulib.github.io/pyvinecopulib/_generate/pyvinecopulib.Vinecop.rosenblatt.html), provided the model has the right tree structure. Here's an example:

``` python
import pyvinecopulib as pv
import numpy as np

data = pv.simulate_uniform(100, 4)

vine_struct = pv.DVineStructure([3, 2, 1, 4])
fit = pv.Vinecop(data, vine_struct)
fit.structure.order
# [3, 2, 1, 4]

u = np.array([[0.2, 0.5, 0.3, 0.1]])
fit.rosenblatt(u)
# array([[0.25030933, 0.61870483, 0.39940915, 0.1       ]])
```

What these numbers mean depends on the vine structure *order*, which we specificed as `[3, 2, 1, 4]` here. Then `rosenblatt(u)` computes the conditional probabilities

p3 = P(U3 <= u3 | U2 = u2, U1= u1, U4 = u4)
p4 = P(U2 <= u2 | U1= u1, U4 = u4)
p1 = P(U1 <= u1 | U4 = u4)
p4 = P(U4 <= u4)

The output is arranged as [p1, p2, p3, p4].

**Comment by kkarrancsu** [comment]
Wonderful - thank you. I will experiment with this, this weekend.

Can you clarify what you mean by "right tree structure"?  Are there only a subset of vine structures that are supported, or is it a matter of correctly inputting the data as you highlighted?

**Comment by tnagler** [comment]
"Right tree structure" refers to the fact that the vine *order* determines which conditional distributions we get. With order `[3, 2, 1, 4]` as above for example, we couldn't get P(U2 <= u2 | U3 = u3, U1= u1, U4 = u4).

**Comment by kkarrancsu** [comment]
Thanks for the clarification. To summarize in my own words - would you say the following statement is accurate?

_The vine order not only determines the formulation of the probability distribution formulation, but also determines which conditional probabilities are possible to be computed with the Rosenblatt transform?_  

To be more specific, suppose we have any VineCop (not just DVine structure, for example) object defined with order `[u_1,u_2,..., u_n]`.  Then is it correct to say that the set of conditional probabilities that can be computed by the Rosenblatt transform are:
```
P[U_1 <= u_1| U_2 <= u_2, ... U_n <= u_n]
P[U_2 <= u_2 | U_3 <= u_3, ... U_n <= u_n]
...
P[U_n <= u_n]
```


A natural follow-up question then is: are there other methods (perhaps not supported by the library) that could be used to compute general conditional probability distributions? 

Thank you again!

**Comment by kkarrancsu** [comment]
Additionally - you noted that the output order in your example is `[p1,p2,p3,p4]`.  Is the input ordered according to the Vine structure, that is, in your example it would have been `[u3, u2, u1, u4]`?

**Comment by tnagler** [comment]
* Yes, the order determines which conditional probabilities you get (also for non-DVines) and the probabilities you listed are the ones corresponding to the order [1, ..., n]. 
* The input to the rosenblatt function is always  [u1, u2, u3, u4], irrespective of the vine order.
* If you want other conditional distributions, the most straightforward method would be numerical integration. If c(u_1, ...., u_n) is the copula density, then for example
$$P(U_1 \le u_1 \mid U_2 = u_2, \dots, U_n = u_n) = \frac{\int_0^{u_1} c(s, u_2, ..., u_n) ds}{ \int_0^{1} c(s, u_2, ..., u_n) ds }$$
This is orders of magnitude slower unfortunately.

**Comment by kkarrancsu** [comment]
Many thanks for answering all of my questions!

**Comment by omerjavaid2525** [comment]
Hello, I have one question. if I want to determine P(X 3 ≥x3∣x1,x2) or F(x1, x2; b) =
∫ ∞
b      pEDP|IMs(x3|x1, x2 )dx3, how can I determine for all possible values of x1 and x2? and plot 3D surface plot. Thank you
