### ISSUE TITLE
Optimal C- or D-Vine model

### ISSUE THREAD

**Issue by doktormo** [vinecopulib/pyvinecopulib#106]
Hey, so if i use
`u = pv.to_pseudo_obs(log_returns.values)`
`controls = pv.FitControlsVinecop(family_set=family_set)`
`cop = pv.Vinecop(u, controls=controls)`
I fit a R-Vine. But how can i restrict it if I want to fit a C- or D-Vine? I see that I can specify the C-Vine structure by myself, but I want to get the optimal C-Vine structure that fits the best to my data.

Thanks :)

**Comment by tnagler** [comment]
That's currently not possible. Why do you want to have a C-vine specifically?

**Comment by doktormo** [comment]
Hm maybe I missunderstood something? I thought this is the top-down sequential estimation method by dißmann. And this method does also work for C- and D-Vines doesnt it?

**Comment by tnagler** [comment]
It could, in general, be used for C- and D-vines by changing the algorithm to not search for maximal spanning trees, but instead search for maximal spanning stars (C-vine) or paths (D-vine), the latter being an NP-hard problem. 

This is not implemented in this library - mainly because we don't think it's useful to restrict to these classes unless one already has a specific order of the variables in mind. Maybe there's an important use-case we're missing, hence my question why you want a C-vine specifically.

**Comment by doktormo** [comment]
I thought about fitting a C- or D-Vine instead of a R-Vine because dißmann's method doesnt provide the optimal model and therefore it is possible that a C- or D-Vine model is better.

Another question: Is there a difference between Vinecop.select and the command of those 3 Lines in my main comment?

**Comment by tnagler** [comment]
About Dissman not optimal: True, but from experience it's extremely rare that the results improve when restricting to C- or D-vines. (I might actually never have seen it.)

About the other question: your main comment and Vinecop.select are exactly the same.

**Comment by doktormo** [comment]
Thank you for your response :)

I have another question: how can I add a rotated copula family to a family set? So if I have a family set

`family_set = [pv.BicopFamily.gaussian, pv.BicopFamily.gumbel, pv.BicopFamily.clayton, pv.BicopFamily.student,
                  pv.BicopFamily.frank, pv.BicopFamily.joe, pv.BicopFamily.bb1, pv.BicopFamily.bb7]`

and I want to fit each copula

`for cop_family in family_set:`
`cop = pv.Bicop(cop_family)`
`cop.fit(data=u)`

how can i add for example the 90° rotated gumbel copula to my family set?

**Comment by tnagler** [comment]
`cop = pv.Bicop(cop_family, rotation=90)`. Not all families have rotation variants though.

**Comment by chienyutseng** [comment]
Hi, I am interested in further discussion on the optimal selection of vine-copula models. 

I'm also working on the selection process for optimal vine-copula models and have a query regarding the capabilities of the `pv.Vinecop.select()` function. Specifically, I'm curious whether it's possible to deduce a C-Vine structure from the function's results without explicitly specifying a C-Vine matrix in the matrix parameter when initializing the `pv.Vinecop()` object. I understand that, by default, the optimal vine-copula model selected tends to be an R-Vine when no particular structure is predetermined as either C-Vine or D-Vine.

**Comment by tnagler** [comment]
As stated above:

> This is not implemented in this library - mainly because we don't think it's useful to restrict to these classes unless one already has a specific order of the variables in mind. Maybe there's an important use-case we're missing, hence my question why you want a C-vine specifically.

**Comment by tvatter** [comment]
This issue seems to be closed too. Feel free to reopen if needed.
