### ISSUE TITLE
selection of best-fit vine-copula

### ISSUE THREAD

**Issue by chienyutseng** [vinecopulib/pyvinecopulib#118]
hi, i am trying to find the optimal vine-coupla for my 4-dimensional data with `Vinecop.select()`, meanwhile using the R-package `VineCopula` for the same procedure due to the support for plotting.
However, the results are different from these two packages. I've tested with some setting condition terms, with different `Bicop.family()` and select criteria with some current summary. It seems that there's not much data gap between the value of `AIC` and `log-lik` from those two packages.

i am wondering if it's acceptable for the difference of the best-fit vine-copula from `pyvinecopulib` and `VineCopula` in R ? 

there's also another issue is that the value of `bic` shows `-inf` in the result from `pyvinecopulib`.

the following is my testing progress:
### pyvinecopulib
```python
U = pv.to_pseudo_obs(dataset)
copula = pv.Vinecop(d=len(dataset.columns))
copula.select(U)
```
<img width="313" alt="image" src="https://github.com/vinecopulib/pyvinecopulib/assets/124143619/62a484ca-d162-4a56-889f-c7b88508e085">

```python
controls = pv.FitControlsVinecop(family_set=[pv.BicopFamily.tll],selection_criterion='aic')
copula.select(U, controls=fit_control)
```
<img width="297" alt="image" src="https://github.com/vinecopulib/pyvinecopulib/assets/124143619/6e9f77be-14ee-4a9a-a3cb-7db69cbd8b6c">

```python
controls = pv.FitControlsVinecop(selection_criterion='aic')
copula_1, copula_1.aic(), copula_1.bic(), copula_1.loglik()
```
<img width="300" alt="image" src="https://github.com/vinecopulib/pyvinecopulib/assets/124143619/808a7448-8810-4286-8e84-15673e8b6529">

### VineCopula 
```R

u_s1 <- data1[, 2]
u_s2 <- data1[, 3]
u_d <- data1[, 4]
u_R <- data1[, 1]

u <- cbind(u_R, u_s1, u_s2, u_d)
u_pseudo <- pseudo_obs(u)

fit_tll <- vinecop(u_pseudo, family_set=c('tll'), selcrit='aic' , show_trace=TRUE)
print(fit_tll)
```
<img width="515" alt="image" src="https://github.com/vinecopulib/pyvinecopulib/assets/124143619/8e60c12a-805e-44d7-a7bc-03a5e602dfdc">

```
fit <- vinecop(u_pseudo, show_trace=TRUE , selcrit='aic')
print(fit4)
contour(fit4)
```
<img width="518" alt="image" src="https://github.com/vinecopulib/pyvinecopulib/assets/124143619/b3e1e8bb-a30f-41a7-a0ff-6abcb3fdee8e">

**Comment by tnagler** [comment]
Both libraries call the same C++ code, so the differences are a little weird. Can you confirm you have the latest version of both libraries?

**Comment by chienyutseng** [comment]
thanks for the advice, but after the upgrade, the fitting results didn't change. 

I would also like to confirm if it is reasonable for the 'bic' value in pyvinecopulib to be 'inf'.

here is the latest version of the package :
```
pyvinecopulib==0.6.4
packageVersion("VineCopula") -> ‘2.5.0’
```

**Comment by tnagler** [comment]
your fit results in R are from the package `rvinecopulib` so please update this package

**Comment by chienyutseng** [comment]
yes, I've also updated package `rvinecopulib`, which the version is `0.6.3.1.1`. However, the difference remains.

**Comment by tvatter** [comment]
I've just compared the results from pyvinecopulib and rvinecopulib with toy datasets and estimated vines are equal when calling the functions with the same parameters. It is expected since, as @tnagler mentioned, both libraries use the same underlying C++ code.

Without a minimum working example (MWE) for us to reproduce, we can't really help unfortunately. I'm going to close the issue for now, but @chienyutseng feel free to reopen if you still need us to have a look and can provide data/code to reproduce the behavior.
