### ISSUE TITLE
D-vines for regression

### ISSUE THREAD

**Issue by 3pwvej** [vinecopulib/pyvinecopulib#122]
Hi, appreciate the work that's gone into this, it's been very useful!

I currently have a use case where the objective is to derive conditional response distributions of a target variable given multiple continuous input features. However, the default fitting function doesn't consistently place the target variable in the last position, hindering the availability of the target distribution conditioned on most or all input features.

My current approach involves comparing model fits for each permutation of variables passed into specific C or D vine structures, where the target variable resides in the last slot, though this isn't scalable. I was wondering if there are recommendations on efficiently specifying a satisfactory variable ordering for the R/D/C vine structure, with the target variable positioned last. One idea I'm considering is building a graph of variable dependencies with Kendall's tau as edge weights, then finding a path of max weight starting with the target node. Would this variable ordering be suitable for passing into a D vine structure?

Additionally, I'm curious about the feasibility of selecting a D-vine structure as outlined in [this paper](https://arxiv.org/pdf/1510.04161.pdf), implemented in your R package (https://github.com/tnagler/vinereg/tree/main). My initial impression is that it may require enhancements to the underlying C++ package. Would it be achievable with the current functionality provided by pyvinecopulib?

Thank you!

**Comment by tnagler** [comment]
Hi, the fitting routine in the `vinereg` R package is implemented [in C++](https://github.com/tnagler/vinereg/blob/main/inst/include/dvine_reg_selector.hpp) based on [`vinecopulib`](https://vinecopulib.github.io/vinecopulib/). In principle one could rewrite the algorithm in Python using the functionality provided by `pyvinecopulib`. You could just use the R package through python with [rpy2](https://rpy2.github.io/) for example.
