### ISSUE TITLE
any conda installation method

### ISSUE THREAD

**Issue by junkai2998** [vinecopulib/pyvinecopulib#125]
i am running `python3.8` on `conda` environment, and installed your package using `pip3` (i found no conda installation option).

so far i ran into problem with two provided methods:
`pip install pyvinecopulib` - gave `/lib64/libm.so.6: version `GLIBC_2.29' not found  problem` during import (no way to upgrade centos7 because the HPC system is not owned by me)

`git clone --recursive https://github.com/vinecopulib/pyvinecopulib.git && pip install ./pyvinecopulib` - gave
```
Processing ./pyvinecopulib
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools>=64.0.0 in ./.conda/envs/root_py38/lib/python3.8/site-packages (from pyvinecopulib==0.6.5.dev0) (69.2.0)
Requirement already satisfied: numpy>=1.14 in ./.conda/envs/root_py38/lib/python3.8/site-packages (from pyvinecopulib==0.6.5.dev0) (1.20.3)
Requirement already satisfied: pybind11>=2.10.0 in ./.conda/envs/root_py38/lib/python3.8/site-packages (from pyvinecopulib==0.6.5.dev0) (2.11.1)
Requirement already satisfied: setuptools-scm>=8.0.0 in ./.conda/envs/root_py38/lib/python3.8/site-packages (from pyvinecopulib==0.6.5.dev0) (8.0.4)
Requirement already satisfied: packaging>=20 in ./.conda/envs/root_py38/lib/python3.8/site-packages (from setuptools-scm>=8.0.0->pyvinecopulib==0.6.5.dev0) (21.3)
Requirement already satisfied: typing-extensions in ./.conda/envs/root_py38/lib/python3.8/site-packages (from setuptools-scm>=8.0.0->pyvinecopulib==0.6.5.dev0) (4.1.1)
Requirement already satisfied: tomli>=1 in ./.conda/envs/root_py38/lib/python3.8/site-packages (from setuptools-scm>=8.0.0->pyvinecopulib==0.6.5.dev0) (2.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.conda/envs/root_py38/lib/python3.8/site-packages (from packaging>=20->setuptools-scm>=8.0.0->pyvinecopulib==0.6.5.dev0) (3.0.4)
Building wheels for collected packages: pyvinecopulib
  Building wheel for pyvinecopulib (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/.conda/envs/root_py38/bin/python /home/junkai.ng/.conda/envs/root_py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp_yw8ddx2
       cwd: /tmp/pip-req-build-408l5vw7
  Complete output (15 lines):
  WARNING setuptools_scm.git git too old -> timestamp is '%cI'
  running bdist_wheel
  running build
  running build_ext
  building 'pyvinecopulib' extension
  creating build
  creating build/temp.linux-x86_64-cpython-38
  creating build/temp.linux-x86_64-cpython-38/src
  /home/user/.conda/envs/root_py38/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/user/.conda/envs/root_py38/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/user/.conda/envs/root_py38/include -fPIC -Ilib/boost -Ilib/eigen -Ilib/eigen/unsupported -Ilib/vinecopulib/include -Ilib/wdm/include -I/tmp/pip-build-env-zrsii08a/overlay/lib/python3.8/site-packages/pybind11/include -I/home/user/.conda/envs/root_py38/include/python3.8 -c src/main.cpp -o build/temp.linux-x86_64-cpython-38/src/main.o -fvisibility=hidden -g0 -std=c++17
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  src/main.cpp:5:10: fatal error: vinecopulib.hpp: No such file or directory
      5 | #include <vinecopulib.hpp>
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/home/user/.conda/envs/root_py38/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pyvinecopulib
Failed to build pyvinecopulib
ERROR: Could not build wheels for pyvinecopulib which use PEP 517 and cannot be installed directly
```

i believe installation via conda is the only way to avoid this problem.
could you provide conda installation option, or point me to manuall installation using conda.

**Comment by junkai2998** [comment]
update:
I was able to install (and import) with
`pip install pyvinecopulib --no-binary ":all:"`
thanks for discussions on [https://github.com/vinecopulib/pyvinecopulib/issues/119](url)

**Comment by tvatter** [comment]
There are multiple things going on here, apologies.

Regarding the initial issue with `pip install pyvinecopulib`, it is similar to #119. I've recently noticed that our binaries are not portable. This was fixed by #380 but I completely forgot to release to PyPi. I just merged into master and tagged the release, which should be available as soon as the GitHub actions complete. In the meantime, `pip install pyvinecopulib --no-binary ":all:"` should work.

Regarding your specific issue with the build failure, I find it weird. I can't replicate this build error either on Debian, Ubuntu, whether in a conda environment or not.

Regarding installing via conda, I've managed to automatically create a recipe that I could use to install pyvinecopulib in a conda environment using [grayskull](https://github.com/conda/grayskull). It is super easy to use. The only reason that the recipe is not pushed to conda forge is that they do not accept recipes that package other software, which we do with boost and Eigen. I could use the boost and Eigen packages from conda there, but then I would need to change the build system as it wouldn't work for PyPI. Long story short: it's easy to do locally but tedious to get it accepted on conda forge :/

**Comment by tvatter** [comment]
Version 0.6.5 is now available on PyPi and the binaries are now properly portable. Can you please test whether it now works for you ? I've tested on a few systems so I'm goig to close for now, but feel free to reopen otherwise.

**Comment by junkai2998** [comment]
btw, just wondering that if there is any group for technical discussion on the usage ?

**Comment by junkai2998** [comment]
> Version 0.6.5 is now available on PyPi and the binaries are now properly portable. Can you please test whether it now works for you ? I've tested on a few systems so I'm goig to close for now, but feel free to reopen otherwise.

thanks, but I'd rather let the other who test the new version (as i dont want to disturb the working installation)
