### ISSUE TITLE
Reference on how to generate samples from vine copulas

### ISSUE THREAD

**Issue by fountaindive** [vinecopulib/pyvinecopulib#127]
Hi,

I was wondering if you could point me to a reference on how to generate samples from vine copula models? In the package I think you call this `simulating`. I had a look around the docs but couldn't find any references that describe how it's implemented.

Many thanks!

**Comment by tnagler** [comment]
The algorithm implements the Rosenblatt transform as described briefly in Section 5 of [this intro paper](https://tnagler.github.io/vine-arisa.pdf).  A detailed algorithm is given in Chapter 6 of [this book](https://link.springer.com/book/10.1007/978-3-030-13785-4).

**Comment by fountaindive** [comment]
Thank you very much!
