### ISSUE TITLE
Fitting a copula with discrete variables

### ISSUE THREAD

**Issue by mike-mendoza** [vinecopulib/pyvinecopulib#130]
Hi all,

I'm trying to fit a copula with 2 discrete variables as follows: 
```
u = pv.to_pseudo_obs(discrete_obs) 
controls = pv.FitControlsBicop(family_set=[pv.BicopFamily.gaussian])
copula = pv.Bicop(data=u, controls=controls,var_types = ['d','d']) 
```
by doing that, the following error arises : `` RuntimeError: data has wrong number of columns; expected: 4 or 4, actual: 2 (model contains 2 discrete variables).``

When using a 4 columns data array, now the error is: ``TypeError: __init__(): incompatible constructor arguments. The following argument types are supported: data: numpy.ndarray[numpy.float64[m, 2]] ``

why is asking for a 4-column data array, the new error suggests a 2-column array again. ?

kind regards

**Comment by tvatter** [comment]
Hi,

First of all, apologies for the delay to answer. I have completely missed this.

I've just noticed that the documentation in the python version of this package is incomplete and clearly insufficient for discrete variables. This will be corrected in a later release.

In the meantime:

* [Documentation of the R version for discrete variables](https://vinecopulib.github.io/rvinecopulib/reference/vinecop.html#discrete-variables) describes what is needed to make it work.
* I just pushed an [example of usage in Python](https://github.com/vinecopulib/pyvinecopulib/blob/discrete_example/examples/discrete_variables.py) that you can refer to.

Let me know if this helps!

**Comment by tvatter** [comment]
Documentation was improved as part of [the latest release](https://github.com/vinecopulib/pyvinecopulib/releases/tag/v0.6.7), which is now also available on PyPI, which closes this issue I think. Feel free to reopen if it's still needed.
