### ISSUE TITLE
Inquiry on Non-Parametric TLL Fitting Formula

### ISSUE THREAD

**Issue by chienyutseng** [vinecopulib/pyvinecopulib#138]
Hello,

I am currently utilizing the package for statistical analysis and have a query regarding the non-parametric Transformation Local Likelihood (TLL) fitting methodology, particularly in its application to estimating the parameter 
𝑘 in AIC calculations.

From my understanding, the TLL approach in the package seems to be linked to kernel density estimation, which is often characterized by its degrees of freedom. I am interested in knowing the specific formula or methodological framework employed for this fitting within the context of AIC computations.

Furthermore, I've encountered several TLL variations such as TLL1, TLL2, TLL1nn, and TLL2nn in different packages, and the references like "Nonparametric estimation of simplified vine copula models: comparison of methods" by Nagler, Schellhase, and Czado (2017) and "Kernel methods for vine copula estimation" by Thomas Nagler (2014) discuss different adaptations of TLL.

Could you please clarify which specific methodology or formula is implemented for the non-parametric TLL fitting in the package? Additionally, which of these publications, or possibly another, would be the most accurate and relevant for me to cite regarding this specific use of TLL in your software?

Thank you for your assistance and for the continuous development of this powerful tool.

**Comment by tnagler** [comment]
Hi! The TLL variations implemented here are `T`, `TLL1`, `TLL2` (in [this paper](https://www.jstatsoft.org/article/view/v084i07)) resp. `tll0`, `tll1`, `tll2` (in [this one](https://www.degruyter.com/document/doi/10.1515/demo-2017-0007/html)). Which of the three methods is used can be controlled by setting the `nonparametric_method` parameter in [`FitControlsBicop`](https://vinecopulib.github.io/pyvinecopulib/_generate/pyvinecopulib.FitControlsBicop.html#pyvinecopulib.FitControlsBicop). The default is `"quadratic"` which corresponds to `TLL2`/`tll2`. Either of the two references mentioned above would be fine to cite, but let me mention that the TLL method was first proposed [here](https://projecteuclid.org/journals/bernoulli/volume-23/issue-3/Probit-transformation-for-nonparametric-kernel-estimation-of-the-copula-density/10.3150/15-BEJ798.full) by Geenens et al. Hope that helps.
