### ISSUE TITLE
Random R-vine structure

### ISSUE THREAD

**Issue by Bluerrror** [vinecopulib/pyvinecopulib#141]
Hi there,

Can you provide R-structure random matrix sample?

Thanks,
Shahab

**Comment by tvatter** [comment]
Actually, I just checked the documentation, and we already have it provided:

https://vinecopulib.github.io/pyvinecopulib/_generate/pyvinecopulib.RVineStructure.simulate.html#pyvinecopulib.RVineStructure.simulate

Let me know if it works for you
