### ISSUE TITLE
How to plot vine copula?

### ISSUE THREAD

**Issue by jacktang** [vinecopulib/pyvinecopulib#145]
Hello, 

I see the vine copula plotting PR is not merged, so is there any example to show how to plot copulas?

**Comment by tvatter** [comment]
Hi, we should be able to merge #146 shortly as the doc is now updated. As soon as it's done, I'll release to PyPI and conda.  In the meantime, one can install from source.

**Comment by tvatter** [comment]
New version is was merged and is now available on PyPI, which closes this issue. Feel free to reopen if it's still needed.
