### ISSUE TITLE
AttributeError: module 'pyvinecopulib' has no attribute 'stats'

### ISSUE THREAD

**Issue by mjholb** [vinecopulib/pyvinecopulib#158]
I have installed pyvinecopulib through conda and also from source but both ways results in the same error. 
What am I missing?

**Comment by tvatter** [comment]
I don't think that we've exposed vinecopulib's stats namespace in pyvinecopulib. A few functions (e.g. to_pseudo_obs and simulate_uniform) are exposed directly as part of the main pyvinecopulib module, as can be seen from the documentation: https://vinecopulib.github.io/pyvinecopulib/

Is there a feature that you are missing? What are you trying to achieve?

**Comment by mjholb** [comment]
When I run the example script vine_copulas_fit_sample.py I get this error - so really the script is wrong. It should just be pv.to_pseudo_obs not pv.stats.to_pseudo_obs

**Comment by tvatter** [comment]
Got it, there was a typo, I made a PR (#159) to correct this oversight. I'm closing since the issue seems to be resolved, but feel free to reopen otherwise.
