### ISSUE TITLE
Package on conda repository

### ISSUE THREAD

**Issue by tnagler** [vinecopulib/pyvinecopulib#2]
https://medium.com/@giswqs/building-a-conda-package-and-uploading-it-to-anaconda-cloud-6a3abd1c5c52

**Comment by slayoo** [comment]
https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by slayoo** [comment]
https://medium.com/@wolfv/making-conda-fast-again-4da4debfb3b7

**Comment by tnagler** [comment]
https://github.com/maxwell-k/conda-appveyor/blob/master/appveyor.yml

**Comment by tnagler** [comment]
https://levelup.gitconnected.com/continuous-deployment-with-travis-and-conda-f385fec1a3f

**Comment by dmey** [comment]
Is this still something on your roadmap?

**Comment by tnagler** [comment]
I guess it's still on the roadmap and we might check in a while if conda has sorted out their issues. 

The reality is that while conda is great from a user's perspective, it's a huge shithole for developers who write lower-level code. Thibault (mostly) and I spent hundreds of developer hours trying to  build & deploy cross-platform for conda - with no success. During the whole time, not one error message was reasonable. Some things we could figure were replaced by another ridiculous error due to breaking changes in the next conda version. Hence, we decided to stick to pypi until conda makes it reasonably easy to deploy the library.

Sorry for the rant ;)

**Comment by dmey** [comment]
I see -- I guess that given that you already distribute binaries for different platforms on PyPi, I see little to no benefit it having this on Conda too, especially given that you have little to no package dependency. My question was mainly a curiosity -- and I agree, loads of pain for little reward in the packaging business 😃.

**Comment by tvatter** [comment]
@dmey, @slayoo, @tnagler, @lorepirri 

See https://github.com/conda-forge/staged-recipes/pull/26628, waiting for review from the conda forge folks.

I'll close one it's merged.

Better late than never.

**Comment by slayoo** [comment]
Kudos @tvatter, for solving the header-file shipment issue!

**Comment by tvatter** [comment]
It works! See #137 for instructions. Closing this one.
