### ISSUE TITLE
C Vine Copulas

### ISSUE THREAD

**Issue by tinoproductions** [vinecopulib/pyvinecopulib#36]
Really great project here.
Is there a way to use C and D vine copulas?

**Comment by tnagler** [comment]
Hi, glad to hear you like it. 

Yes, both C- and D-vines are sub-classes of the more general R-vine copulas implemented in this library. If you want to focus on C or D vines, you currently have to set up an appropriate structure matrix ([here](https://vinecopulib.github.io/vinecopulib/classvinecopulib_1_1_r_vine_structure.html)'s a short explanation). 

However, we hope to release a new version in the next couple of days and this will include some [convenience classes](https://github.com/vinecopulib/vinecopulib/pull/464) that makes this easier.

**Comment by tvatter** [comment]
C and D vines are now implemented!

**Comment by tinoproductions** [comment]
That is amazing. Well done team!
