### ISSUE TITLE
C-vine copula example 

### ISSUE THREAD

**Issue by AmosJoseph** [vinecopulib/pyvinecopulib#50]
Excuse me,do you have any example for C-vine copula?

How to implement the C-vine copula?

I deeply appreciate for your time and looking forward to your reply!

Best Regards!

Yours sincerely!

**Comment by AmosJoseph** [comment]
Parton!
How to implement the copula density?

**Comment by tinoproductions** [comment]
Hi,
I would also like for more examples to be provided. I can see this being a very useful package, but I can't seem to work out how everything fits together.
Many thanks

**Comment by tnagler** [comment]
I added a short example at the end of our [example notebook](https://github.com/vinecopulib/pyvinecopulib/blob/update-ex/examples/vine_copulas.ipynb). The examples are admittedly quite minimal so far and we hope to extend them at some point. Any help with that would be very much appreciated by the way ;) Neither of us are active python users, so any community input is very helpful.

In the meanwhile, you could have a look at our [online API documentaion](https://vinecopulib.github.io/pyvinecopulib/).

**Comment by tinoproductions** [comment]
That is very helpful thanks!
I am slowly experimenting and things are happening.

So far managed to do a similar example to yours with 4 assets:
u_pairs_data df consisting of 4 assets
cop = pv.Vinecop(data=u_pairs_data, structure = pv.CVineStructure([2,3,4,1]))
print(cop)
<pyvinecopulib.Vinecop>
** Tree: 0
2,1 <-> Frank, parameters = 3.00001
3,1 <-> BB8 180°, parameters =   4.3091
0.705418
4,1 <-> Gumbel 180°, parameters = 1.53467
** Tree: 1
2,4 | 1 <-> Frank, parameters = 1.08527
3,4 | 1 <-> Gaussian, parameters = 0.338489
** Tree: 2
2,3 | 1 <-> Frank, parameters = 1.7041

the odd thing Is that I am expecting 2,3 | 1 in Tree 1
and 34 | 12 in Tree 2

as per page 11 of http://www.plantbreeding.wzw.tum.de/fileadmin/w00bdb/www/kraemer/Vines.pdf

Any ideas?

Keep up the great work and I will try and contribute as much as possible

**Comment by tnagler** [comment]
You need to change the order of the C-vine to `pv.CVineStructure([4,3,2,1])`. The order is the sequence of root nodes in reverse. 

Let's take `[4,3,2,1]` as an example. The index `1` is last, so it is the root node of the first tree (all other nodes are connected to `1`). It also means, that in the following tree all edges will have `1` in the conditioning set, i.e, look like `i, j | 1`. The index `2` is second-to-last, so it is the root node of the second tree (all other nodes are connected to `12`).  Then the following tree will have `1, 2` in the conditioning set. And so on...

(Also, there's a little [bug](https://github.com/vinecopulib/vinecopulib/pull/484) in the print function, will be fixed soon.)

**Comment by AmosJoseph** [comment]
Ok,Thank you so much for your help!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Thomas Nagler"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 晚上9:16
收件人: "vinecopulib/pyvinecopulib"<pyvinecopulib@noreply.github.com&gt;; 
抄送: "Joseph"<544591929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vinecopulib/pyvinecopulib] C-vine copula example  (#50)




You need to change the order of the C-vine to pv.CVineStructure([4,3,2,1]). The order is the sequence of root nodes in reverse.
 
Let's take [4,3,2,1] as an example. The index 1 is last, so it is the root node of the first tree (all other nodes are connected to 1). It also means, that in the following tree all edges will have 1 in the conditioning set, i.e, look like i, j | 1. The index 2 is second-to-last, so it is the root node of the second tree (all other nodes are connected to 12).  Then the following tree will have 1, 2 in the conditioning set. And so on...
 
(Also, there's a little bug in the print function, will be fixed soon.)

**Comment by tinoproductions** [comment]
The bug you mention above has to do with the last tree not being conditioned on 2 variables right?

**Comment by tnagler** [comment]
Yes.

**Comment by tinoproductions** [comment]
Love your work sir!

**Comment by tvatter** [comment]
The examples are now in the master branch with #61.
