### ISSUE TITLE
Artifacts storage in git repo

### ISSUE THREAD

**Issue by dmey** [vinecopulib/pyvinecopulib#59]
You may have had very good reasons for doing so but I noticed that you are storing the Boost library archive in this git repo. Just as you have only made one commit I though I'd mention it now as you would still be able to 'undo' this before you add more commits. I noticed that Boost is also available at https://github.com/boostorg/boost so you should be able to include it as a submodule like you did for the others.

**Comment by tnagler** [comment]
Yeah that has a good reason ;) 

Boost is huuuuge and we only need a fairly small subset of it. https://github.com/boostorg/boost including submodules is roughly 1.7 GB. Forcing every user or build system to clone this is not reasonable. The archive we have in our library is just 10 MB and includes only what we need.
