### ISSUE TITLE
How to use sets of families for the BicopFamily class

### ISSUE THREAD

**Issue by dmey** [vinecopulib/pyvinecopulib#63]
I tried to set the controls for a set of family rather than its members as mentioned in the docs (https://vinecopulib.github.io/pyvinecopulib/_generate/pyvinecopulib.BicopFamily.html#pyvinecopulib.BicopFamily) as:

```py
pv.FitControlsVinecop(family_set=[pv.BicopFamily.all])
```

however these families are not members of the BicopFamily and result in `AttributeError: type object 'pyvinecopulib.BicopFamily' has no attribute 'all'`. Is this meant to be called in a different way?

**Comment by tvatter** [comment]
The sets are part of the main namespace of `pyvinecopulib`, so you can do `pv.all`.

![image](https://user-images.githubusercontent.com/5273142/87549289-a46b6480-c67b-11ea-8151-a836127d9c23.png)

**Comment by tnagler** [comment]
Ah.. We should clarify this in the documentation. Also, wouldn't it be better to have this as `pv.families.all` or similar?

**Comment by tvatter** [comment]
Agreed for the clarifications. Regarding the namespace, I'm not sure that it's worth it. If anything, I would actually have `pv.BicopFamily.all` (i.e., an object of class `BicopFamily` to return a set of objects).

**Comment by dmey** [comment]
I see, OK and then this is set by passing e.g. `family_set=pv.all` to FitControlsVinecop. So in the example above this would be:
```
pv.FitControlsVinecop(family_set=pv.all)
```
Thanks for the clarification.

**Comment by tnagler** [comment]
Wouldn't it be confusing (if at all possible) to have an enum that holds a list of enums of the same type?

**Comment by tvatter** [comment]
@dmey exactly! However, `pv.all` is the default anyway :)

**Comment by tvatter** [comment]
@tnagler The enum would'nt "hold" the list, it would just have a method allowing to create such a list.

**Comment by tvatter** [comment]
@dmey I just noticed that the documentation of three of those sets was incorrect, see #65 (it's just the doc, the sets are actually available)

**Comment by tvatter** [comment]
Since the doc has been corrected for a while, I'm closing. Feel free to reopen if needed.

**Comment by tvatter** [comment]
Actually, arguments of the controls should be better documented anyway. I'm reopening.

**Comment by kevindarby** [comment]
Perhaps related, is there a way to specify the family for each bicop and then fit them to data?

Do I have to fit each bicop separately then?  If so, does the bicop.fit() just take the leftmost columns in the dataset?

For instance, I'd like to set up:

>tree0 = [
         pv.Bicop(pv.BicopFamily.bb7, rotation = 0), #, parameters = None), 
         pv.Bicop(pv.BicopFamily.bb7, rotation = 0), 
         pv.Bicop(pv.BicopFamily.indep, rotation = 0), 
         pv.Bicop(pv.BicopFamily.bb7, rotation = 0), 
         pv.Bicop(pv.BicopFamily.bb7, rotation = 0),
        ]
tree1 = [
         pv.Bicop(pv.BicopFamily.bb7, rotation = 0), 
         pv.Bicop(pv.BicopFamily.bb7, rotation = 0), 
         pv.Bicop(pv.BicopFamily.bb7, rotation = 0), 
         pv.Bicop(pv.BicopFamily.bb7, rotation = 0),
        ]
...

then 

> order = np.arange(1, len(data.columns) + 1)
> vine_struct = pv.DVineStructure(order) #eg [1,2,3...
> fit = pv.Vinecop(vine_struct, pair_copulas = [tree0, tree1, tree2, tree3, tree4])

but now 

> fit.select(data)  

can change families

and 
> controls = pv.FitControlsVinecop(family_set=[pv.BicopFamily.bb7, pv.BicopFamily.indep], 
> fit.select(data, controls = controls)

can make some bb7 and some indep,

**Comment by tvatter** [comment]
@kevindarby Since last release, we now have a fit method, so it is indeed possible. See [Vinecop.fit](https://vinecopulib.github.io/pyvinecopulib/_generate/pyvinecopulib.Vinecop.fit.html). I'm closing but feel free to reopen if this does not solve your issue.
