### ISSUE TITLE
Add support to return/load json string

### ISSUE THREAD

**Issue by dmey** [vinecopulib/pyvinecopulib#66]
For interoperability with other scripts/libraries it would be useful to add support to to return/load a json string directly instead of dumping to file first.

**Comment by tvatter** [comment]
As mentioned a few times as answers to the other issues that you raised in vinecopulib, we are using [boost property trees](https://www.boost.org/doc/libs/1_65_1/doc/html/property_tree.html), and thus are constrained by what [boost property trees](https://www.boost.org/doc/libs/1_65_1/doc/html/property_tree.html) can do. Please read the documentation of [boost property trees](https://www.boost.org/doc/libs/1_65_1/doc/html/property_tree.html) before asking something that [boost property trees](https://www.boost.org/doc/libs/1_65_1/doc/html/property_tree.html) cannot do.

I'm referencing the other issues here:

- https://github.com/vinecopulib/vinecopulib/issues/504
- https://github.com/vinecopulib/vinecopulib/issues/505
- https://github.com/vinecopulib/vinecopulib/issues/506
