### ISSUE TITLE
pickle pyvinecopulib.Bicop object 

### ISSUE THREAD

**Issue by mike-mendoza** [vinecopulib/pyvinecopulib#88]
Hi all, 

I'm trying to pickle a list of pyvinecopulib.Bishop objects for later use but got : TypeError: cannot pickle 'pyvinecopulib.Bicop' object
Is there any solution to that? 

Regards

**Comment by tvatter** [comment]
In the medium term, we should make the Bicop class pickelable as explained here https://pybind11.readthedocs.io/en/stable/advanced/classes.html#pickling-support

But this is not implemented yet.

As a short term fix, my suggestion would be to use save the models into files using the `to_json` method. Would that work for you?

**Comment by tvatter** [comment]
https://vinecopulib.github.io/pyvinecopulib/_generate/pyvinecopulib.Bicop.to_json.html#pyvinecopulib.Bicop.to_json

**Comment by mike-mendoza** [comment]
Thanks for the answer, that will work!
