### ISSUE TITLE
Example of constructing a R-copula

### ISSUE THREAD

**Issue by LuigiDarkSimeone** [vinecopulib/pyvinecopulib#89]
Hi thanks for such a great work.
Really appreciated. I can't really get a solution to my problem by just looking at your examples.

I would like to build a R-vine structure copula for my dataset (many variables >>2).
Due to the high dimensionality of the dataset, a composite multivariate copula can be very diffcult to fit correctly without overly generalizing too much therefore I want to build it as many bivariates. Each bivariate copula is specified to belong to the Clayton copula family to emphasize tail dependency. I want to model the marginal distributions using the empirical probability integral transform on the time series, generating the empirical distribution.

The objective is then, once obtained the above to resample from it, with a Montecarlo approach.
Can you please suggest how to set up the parameters?

Many thanks

**Comment by tnagler** [comment]
Hi! If this is all you need, you might want too into [synthia](https://github.com/dmey/synthia), which is a wrapper around pyvinecopulib, see the example here: https://dmey.github.io/synthia/examples/multivariate-vine.html#Fit-a-Vine-copula-with-pyvinecopulib%E2%80%99s-backend

You can use 
``` py
ctrl = pv.FitControlsVinecop(family_set=[pv.BicopFamily.clayton])
```
to restrict to clayton copulas. I would recommend against this though and let the algorithm select the family that best fits the data:
``` py
ctrl = pv.FitControlsVinecop(family_set=[pv.parametric])
```

**Comment by LuigiDarkSimeone** [comment]
thanks a lot for your prompt answer.
Yes you are right, better to let it choose itself the best family.

do you think it is right to build a copula as I described above? I mean, create many bivariates rather than one whole fit?
Can somehow the bivariates be marged together afterwards? In principla I am quite sure of this way of proceeding but again I am afraid I can't really get a way of doing it with pyvinecopulib

Thanks in advance

**Comment by tnagler** [comment]
I'm not sure I understand how you want to build the copula. Vine copulas do merge multiple bivariate copulas into one single fit, so there's nothing you would need to do manually.

**Comment by tvatter** [comment]
I'm going to close this as it seems stale. @LuigiDarkSimeone feel free to reopen if you still need help.
