### ISSUE TITLE
Conditional probability possible? 

### ISSUE THREAD

**Issue by markdregan** [vinecopulib/pyvinecopulib#90]
Hi - I’m hoping I could get advise/guidance. I’m trying to use copula to model the spread between financial asset prices so that I can compute the conditional probability of the spread being wider than one would probabilistically expect. 

My question: what is the best way to leverage this library to compute conditional probabilities for observed data? More specifically, for a bivariate distribution, I’ll want to compute conditional probability of P(A > a | B = b). See attached screenshot for details.

![screen_shot_2022-03-24_at_3.05.40_pm.png](https://user-images.githubusercontent.com/1952278/161157266-d66e3f2f-b2ad-4614-b5f3-f2766638fdab.png)

Appreciate any guidance. Mark

**Comment by tvatter** [comment]
Hi,

The h-function is what you are looking for:

https://vinecopulib.github.io/pyvinecopulib/_generate/pyvinecopulib.Bicop.hfunc1.html

See the following notebook for examples:

https://github.com/vinecopulib/pyvinecopulib/blob/master/examples/bivariate_copulas.ipynb

Thibault

**Comment by markdregan** [comment]
👍👍 thank you kindly
