### ISSUE TITLE
Fix non-virtual destructor compiler error

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/pyvinecopulib#91]
On some compilers, one might get:

"warning: 'vinecopulib::tools_select::VinecopSelector' has virtual functions but non-virtual destructor [-Wnon-virtual-dtor]"

This can be solved by adding  "virtual ~VinecopSelector() = default;" in line 100 of tools_select.hpp.

**Comment by tnagler** [comment]
fixed in https://github.com/vinecopulib/vinecopulib/pull/552
