### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ~/Anaconda3/envs/py38/lib/python3.8/site-packages/pyvinecopulib.cpython-38-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by RihuiAn** [vinecopulib/pyvinecopulib#92]
I run code on the high-performance computer in school. I don't have permission to upgrade the version of GLIBC_2.29.

What else can I do if I can't upgrade the GLIBC?

**Comment by tnagler** [comment]
Hard to say what you can do, as it's not even clear at which stage or why the error occurs. Usually this is a cross-compiling issue. That is, the program was not compiled on the system where it is run.

**Comment by RihuiAn** [comment]
Thank you for your kind reply!
I can install this package with PIP. But it reports the error when "import pyvinecopulib"
My version is glibc2.17, but I don't have administrator privileges to upgrade it to 2.29.
I want to know how I can modify the package to run on glibc2.17.

**Comment by slayoo** [comment]
Please perhaps try pip-installing from source, like:
```
$ pip install --verbose "git+https://github.com/vinecopulib/pyvinecopulib#egg=pyvinecopulib"
```

**Comment by RihuiAn** [comment]
Cloning https://github.com/vinecopulib/pyvinecopulib to /tmp/pip-install-6p_rfzul/pyvinecopulib_1852ea3b762548dbb4a671ad318e3e13
  Running command git clone -q https://github.com/vinecopulib/pyvinecopulib /tmp/pip-install-6p_rfzul/pyvinecopulib_1852ea3b762548dbb4a671ad318e3e13
  fatal: unable to access 'https://github.com/vinecopulib/pyvinecopulib/': Failed connect to github.com:443; Connection timed out
WARNING: Discarding git+https://github.com/vinecopulib/pyvinecopulib#egg=pyvinecopulib. Command errored out with exit status 128: git clone -q https://github.com/vinecopulib/pyvinecopulib /tmp/pip-install-6p_rfzul/pyvinecopulib_1852ea3b762548dbb4a671ad318e3e13 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyvinecopulib (unavailable) (from versions: 0.2.0, 0.5.0, 0.5.2, 0.5.4, 0.5.5, 0.6.0, 0.6.1)
ERROR: No matching distribution found for pyvinecopulib (unavailable)



I have tried  pip-installing from the source, but it does not work. Is there any other solution?

**Comment by slayoo** [comment]
Well, it says: `Failed connect to github.com:443; Connection timed out` - there is some issue connecting to github, this is surely solvable.

**Comment by RihuiAn** [comment]
By the way, I can use the package smoothly on my personal computer, because the version is glibc2.21.
Is there any way to make the package run in the glibc<=2.17? 
Or do you know how to configure the environment without administrator privileges?

**Comment by slayoo** [comment]
If http connections to github are blocked, you can try over ssh (which requires [registering an ssh key with github](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)):
```
$ git clone --recurse-submodules --shallow-submodules --depth 1 git@github.com:vinecopulib/pyvinecopulib.git
$ VERBOSE=1 pip install --verbose -e pyvinecopulib
```
>  Or do you know how to configure the environment without administrator privileges?

You can, e.g., set up a local Gentoo prefix environment which will compile a brand new glibc for you (and Python, and many many other things - takes time, but is fully automated and tends to work on HPC machines out of the box): https://wiki.gentoo.org/wiki/Prefix

**Comment by tvatter** [comment]
As an aside, we do not require a specific version of glibc. I think that it must be one of our dependencies.

**Comment by RihuiAn** [comment]
Thanks a lot for your help. The problem has been solved when I upgrade the version to glibc2.31. I think a specific version of glibc is required due to some dependencies (pyvinecopulib.cpython-38-x86_64-linux-gnu.so).
