### ISSUE TITLE
Different results between pyvinecopulib and rvinecopulib (based on VineCopula)

### ISSUE THREAD

**Issue by RihuiAn** [vinecopulib/pyvinecopulib#94]
pv.Bicop return the wrong family and parameters when chosing the rotated copula (except 180°).
For example, simulate from a bivariate BB8 Copula
r('set.seed(123)')
sim=r('sim=BiCopSim(10000,30,-6,-0.5)')

by pyvinecopulib:
control = pv.FitControlsBicop(family_set=pv.one_par + pv.two_par, parametric_method='mle', selection_criterion='bic')
f1 = pv.Bicop(sim, controls=control)
str(f1)
>> <pyvinecopulib.Bicop> BB8 90°, parameters =  8,  0.403979

by VineCopula:
r.assign('u', sim[:, 0])
r.assign('v', sim[:, 1])
f2 = r('f2 = BiCopSelect(u, v, familyset = 1:10, selectioncrit = "BIC", rotations = TRUE, indeptest = FALSE, level = 0.05)')
str(f2)
>> 'Bivariate copula: Rotated BB8 90 degrees (par = -6, par2 = -0.51, tau = -0.37) \n'

**Comment by tnagler** [comment]
You simulate from a 90 degree BB8 and both libraries select a 90 degree BB8, so I'm not sure what you mean by "wrong family".

**Comment by RihuiAn** [comment]
by pyvinecopulib:
>> f1.family
<BicopFamily.bb8: 10>

by VineCopula:
>> r('f2$familyname')
['Rotated BB8 90 degrees']
>> r('f2$family')
array([30.])

pyvinecopulib shows 10 (family without rotated), but VineCopula shows 30 (the rotated family)

**Comment by RihuiAn** [comment]
I think I was blinded by str(f1), which shows BB8 90°, because the parameters = 8, 0.403979 is still based on BB8 family.
"The first parameter of the BB8 copula has to be in the interval [1,8]."
 "The first parameter of the rotated BB8 copula has to be in the interval [-8,-1]."

**Comment by tnagler** [comment]
vinecopulib has an extra parameter for the rotation and the family is specified by their name.

**Comment by RihuiAn** [comment]
So, despite the same copula family, the parameters are different, right?

**Comment by tnagler** [comment]
Yes. There's no guarantee they should be the same, since VineCopula and rvinecopulib are two completely separate implementations and use different optimizers. In that case, rvinecopulib seems off by a decen margin, so I'll probably check what causes the difference when I find time.

**Comment by RihuiAn** [comment]
Thank you for your reply. I have another question about BiCopGofTest in VineCopula.

Despite the default value B=100 is taken, the computation is still too long for me. Do you have any better suggestions on how to choose B value (number of bootstrap samples) considering the number of samples? Or is there a more efficient parallel computing method? 

And do you have any plans for further development of pyvinecopulib? (It is a pity that pyvinecopulib has fewer functions than VineCopula, despite with shorter runtimes and lower memory consumption)

**Comment by tnagler** [comment]
You can use `method = "white"` where bootstrapping is not necessary. [For the future: Questions about VineCopula should be asked in the corresponding.]

There will be further development of pyvinecopulib, but not all of the features in `VineCopula` will be replicated. (GoF tests are not high up on the todo list, see https://github.com/vinecopulib/vinecopulib/issues/376)

**Comment by RihuiAn** [comment]
Thanks again for your above clarification!
