### ISSUE TITLE
Conditional probability (conditional CDF)

### ISSUE THREAD

**Issue by alex33d** [vinecopulib/pyvinecopulib#96]
Hi

Can not figure out if there is a method to calculate conditional probability (get conditional CDF) of a fitted vine copula for the response variable given target variables?

Essentially is there a simple method implemented to get P(U<=u | V=v, X=x...)?

Thanks!

**Comment by tnagler** [comment]
Yes, via the [Rosenblatt transform](https://vinecopulib.github.io/pyvinecopulib/_generate/pyvinecopulib.Vinecop.rosenblatt.html) mentioned in Section 5 [here](https://www.annualreviews.org/doi/full/10.1146/annurev-statistics-040220-101153) and many papers on vine copula regression. Two things to look out for:
- The index of the response variable has to be in the bottom left corner of the structure matrix.
- The probability(U_j | U_{{1, d} \ j}) is in the j-the column of the output.

**Comment by tnagler** [comment]
Documentation will be updated with the next release. Preview: ![image](https://user-images.githubusercontent.com/8761435/179525346-eeb25acf-64ad-446d-9c01-1dcb1456414c.png)
